#Example load balancer service
#Access for SQL server, AG listener, and DxE management
apiVersion: v1
kind: Service
metadata:
  name: influxdb-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.192.6.0
  selector:
    app: influxdb
  ports:
  - name: web
    protocol: TCP
    port: 8086
    targetPort: 8086
