kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mssql
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y

    [coredump]
    captureminiandfull = true
    coredumptype = full

    [language]
    lcid = 1033

    [filelocation]
    defaultdatadir = /var/opt/mssql/userdata
    defaultlogdir = /var/opt/mssql/userlog
    defaultbackupdir = /var/opt/mssql/backup

    [sqlagent]
    enabled = true

    [network]
    privilegedadaccount = sqlk8ssvc
    kerberoskeytabfile = /var/opt/mssql/secrets/mssql.keytab
