#Example load balancer service
#Access for SQL server, AG listener, and DxE management
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.192.1.13
  selector:
    app: grafana
  ports:
  - name: web
    protocol: TCP
    port: 3000
    targetPort: 3000
