{
 "title": "SQL Container Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"sql_instance\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   },
   {
    "name": "datasource",
    "query": "f2897f6e-4b6d-4055-a061-555b6dc76574"
   }
  ]
 },
 "panels": [
  {
   "title": "Percent CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_cpu\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Memory Manager (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"server_memory\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n"
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Memory Manager\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Target Server Memory (KB)\" or r[\"counter\"] == \"Total Server Memory (KB)\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Transactions/sec",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Databases\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Transactions/sec\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"instance\", \"_value\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "Transactions_sec-_Total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Batch Requests/sec",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:SQL Statistics\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Batch Requests/sec\" or r[\"counter\"] == \"SQL Compilations/sec\" or r[\"counter\"] == \"SQL Re-Compilations/sec\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=~", "value": "/Batch_Requests_sec-[ ]{0,1}/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait Statistics (Wait time ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_wait_time_ms",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_waitstats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wait_time_ms\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"wait_type\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait Statistics (Waiting task count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_waiting_tasks_count",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_waitstats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"waiting_tasks_count\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"wait_type\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Buffer Manager\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Buffer cache hit ratio\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Cache - Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Buffer Manager\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Page lookups/sec\" or r[\"counter\"] == \"Page reads/sec\" or r[\"counter\"] == \"Page writes/sec\" or r[\"counter\"] == \"Readahead pages/sec\" or r[\"counter\"] == \"Checkpoint pages/sec\" or r[\"counter\"] == \"Lazy writes/sec\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Access Methods\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Full Scans/sec\" or r[\"counter\"] == \"Index Searches/sec\" or r[\"counter\"] == \"Page Splits/sec\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Buffer Manager\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Page life expectancy\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Database Cache",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_memory_clerks\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"size_kb\")\r\n  |> filter(fn: (r) => r[\"clerk_type\"] == \"Buffer Pool\" or r[\"clerk_type\"] == \"Connection Pool\" or r[\"clerk_type\"] == \"Log Pool\" or r[\"clerk_type\"] == \"Object Plans\" or r[\"clerk_type\"] == \"SQL Plans\" or r[\"clerk_type\"] == \"SQL Optimizer\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"clerk_type\", \"_value\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Database_Cache_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Optimizer",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Optimizer_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "SQL Cache",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/SQL_Cache_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Log Pool",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Log_Pool_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Connection",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Connection_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Lock",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Lock_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_latency_ms\" or r[\"_field\"] == \"write_latency_ms\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"_field\", \"logical_filename\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Disk IOPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reads\" or r[\"_field\"] == \"writes\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"_field\", \"logical_filename\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\" or r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"_field\", \"logical_filename\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Data File Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Database Cache",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Databases\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Data File(s) Size (KB)\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"instance\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Database_Cache_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Log File Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Database Cache",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Databases\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Log File(s) Size (KB)\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"instance\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=~",
       "value": "/Database_Cache_Memory_\\(KB\\)-[ ]{0,1}/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Transactions/sec",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Latches\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Latch Waits/sec\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "Transactions_sec-_Total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Locks\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Lock Waits/sec\" or r[\"counter\"] == \"Lock Timeouts/sec\" or r[\"counter\"] == \"Number of Deadlocks/sec\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"Total\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Databases\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Log Flushes/sec\" or r[\"counter\"] == \"Log Flush Wait Time\" or r[\"counter\"] == \"Write Transactions/sec\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"Total\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    }
   ]
  },
  {
   "title": "SQL Server Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:General Statistics\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Logins/sec\" or r[\"counter\"] == \"Logouts/sec\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:General Statistics\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"User Connections\" or r[\"counter\"] == \"Processes blocked\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    }
   ]
  },
  {
   "title": "AlwaysOn (Transaction Delay)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Database Replica\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Transaction Delay\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"instance\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "type_instance",
       "operator": "=",
       "value": "\\\"Transaction_Delay.\"\\"
      }
     ]
    }
   ]
  },
  {
   "title": "AlwaysOn",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Log Bytes Flushed/sec",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "dbi_perf_stats_value",
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Database Replica\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Log Apply Ready Queue\" or r[\"counter\"] == \"Recovery Queue\" or r[\"counter\"] == \"Log Apply Pending Queue\" or r[\"counter\"] == \"Redone Bytes/sec\" or r[\"counter\"] == \"Log Bytes Received/sec\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"Total\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "Log_Bytes_Flushed_sec-_Total" }
     ]
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Availability Replica\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Bytes Sent to Transport/sec\" or r[\"counter\"] == \"Bytes Sent to Replica/sec\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"Total\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    },
    {
     "query": "\r\nfrom(bucket: \"sqlmon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"SQLServer:Databases\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Log Bytes Flushed/sec\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"Total\")\r\n  |> filter(fn: (r) => r[\"measurement_db_type\"] == \"SQLServer\")\r\n  |> filter(fn: (r) => r[\"sql_instance\"] == \"${hostname}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"counter\", \"_value\"])"
    }
   ]
  }
 ]
}